name: Practicing the Grid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59324
title: 'This is my site for practicing on the grid. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#debe2f'
    - '#ffff00'
    - '#808000'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
