name: Practicing the Grid
favicon: null
layout_spectrum: 0.62838
typography_spectrum: 0.52568
title: 'This is my site for practicing on the grid. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68656b'
    - '#000000'
    - '#404040'
    - '#800080'
    - '#000080'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
